query GetPlannerItems($weekStart: String!) {
	getPlannerItems(weekStart: $weekStart) {
		id
		dishId
		day
		mealTime
		dish {
			id
			name
			category
			imageUrl
			calories
			description
		}
	}
}

mutation SavePlannerItems($items: [PlannerItemInput!]!, $weekStart: String!) {
	savePlanner(items: $items, weekStart: $weekStart)
}
