query GetPlannerItems($startDate: String!, $endDate: String!) {
	getPlannerItems(startDate: $startDate, endDate: $endDate) {
		id
		dishId
		date
		mealTime
		menuPlanId
		dish {
			id
			name
			category
			imageUrl
			calories
			description
		}
	}
}

query GetMenuPlans($startDate: String!, $endDate: String!) {
	getMenuPlans(startDate: $startDate, endDate: $endDate) {
		id
		date
		week
		day
		items {
			id
			dishId
			mealTime
			dish {
				id
				name
				imageUrl
				calories
			}
		}
	}
}

mutation SavePlannerItems(
	$items: [PlannerItemInput!]!
	$startDate: String!
	$endDate: String!
) {
	savePlanner(items: $items, startDate: $startDate, endDate: $endDate)
}
